name: wangzhe
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.11.4=haa95532_0
  - expat=2.7.3=h9214b88_0
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.0.18=h543e019_0
  - pip=25.3=pyhc872135_0
  - python=3.12.12=h716150d_1
  - setuptools=80.9.0=py312haa95532_0
  - sqlite=3.51.0=hda9a48d_0
  - tk=8.6.15=hf199647_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py312haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
    - certifi==2025.11.12
    - chardet==4.0.0
    - charset-normalizer==3.4.4
    - colorama==0.4.6
    - conda-pack==0.8.1
    - elasticsearch==7.10.1
    - elasticsearch-dsl==7.3.0
    - filelock==3.19.1
    - fsspec==2025.9.0
    - huggingface-hub==0.36.0
    - idna==2.10
    - jinja2==3.1.6
    - markupsafe==2.1.5
    - modelscope==1.32.0
    - mpmath==1.3.0
    - networkx==3.5
    - numpy==2.2.6
    - opencv-python==4.12.0.88
    - packaging==25.0
    - pillow==11.3.0
    - pydantic==1.9.2
    - pygame==2.6.1
    - python-dateutil==2.9.0.post0
    - pyyaml==6.0.3
    - regex==2025.11.3
    - requests==2.25.1
    - safetensors==0.6.2
    - six==1.17.0
    - sympy==1.14.0
    - tokenizers==0.22.1
    - torch==2.9.1+cu128
    - torchvision==0.24.1+cu128
    - tqdm==4.67.1
    - transformers==4.57.1
    - typing_extensions==4.15.0
    - urllib3==1.26.20
prefix: C:\Users\11451\Anaconda3\envs\wangzhe

